//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ocrstudio {

using System.Runtime.InteropServices;
using System;
using System.Text;

class csocrstudiosdkPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="SWIGRegisterExceptionCallbacks_csocrstudiosdk")]
    public static extern void SWIGRegisterExceptionCallbacks_csocrstudiosdk(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_csocrstudiosdk")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_csocrstudiosdk(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_csocrstudiosdk(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_csocrstudiosdk(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="SWIGRegisterStringCallback_csocrstudiosdk")]
    public static extern void SWIGRegisterStringCallback_csocrstudiosdk(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_csocrstudiosdk(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static csocrstudiosdkPINVOKE() {
  }


public class SimpleMarshaler : ICustomMarshaler {
    static SimpleMarshaler myself = new SimpleMarshaler();

    public object MarshalNativeToManaged(IntPtr pNativeData) {
        int size_buffer = 0;
        while (Marshal.ReadByte(pNativeData, size_buffer) != 0) {
            ++size_buffer;
        }
        byte[] byte_buffer = new byte[size_buffer];
        Marshal.Copy((IntPtr)pNativeData, byte_buffer, 0, size_buffer);
        return Encoding.UTF8.GetString(byte_buffer);
    }

    public IntPtr MarshalManagedToNative( Object ManagedObj ) => throw new NotImplementedException();

    public void CleanUpNativeData( IntPtr nativeData ) {
        Marshal.FreeHGlobal(nativeData);
    }

    public void CleanUpManagedData( Object ManagedObj ) => throw new NotImplementedException();
    public int GetNativeDataSize() => throw new NotImplementedException();

    public static ICustomMarshaler GetInstance(string cookie) {
        return myself;
    }
}


  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKException")]
  public static extern void delete_OCRStudioSDKException(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKException__SWIG_0")]
  public static extern global::System.IntPtr new_OCRStudioSDKException__SWIG_0(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKException__SWIG_1")]
  public static extern global::System.IntPtr new_OCRStudioSDKException__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKException_Type")]
  public static extern string OCRStudioSDKException_Type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKException_Message")]
  public static extern string OCRStudioSDKException_Message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKString")]
  public static extern void delete_OCRStudioSDKString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKString__SWIG_0")]
  public static extern global::System.IntPtr new_OCRStudioSDKString__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKString__SWIG_1")]
  public static extern global::System.IntPtr new_OCRStudioSDKString__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKString__SWIG_2")]
  public static extern global::System.IntPtr new_OCRStudioSDKString__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKString_CStr")]
  public static extern string OCRStudioSDKString_CStr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKString_Size")]
  public static extern int OCRStudioSDKString_Size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKDelegate")]
  public static extern void delete_OCRStudioSDKDelegate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKDelegate_Callback")]
  public static extern void OCRStudioSDKDelegate_Callback(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKDelegate")]
  public static extern global::System.IntPtr new_OCRStudioSDKDelegate();

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKDelegate_director_connect")]
  public static extern void OCRStudioSDKDelegate_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, OCRStudioSDKDelegate.SwigDelegateOCRStudioSDKDelegate_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_PagesCount")]
  public static extern int OCRStudioSDKImage_PagesCount(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_PageName")]
  public static extern global::System.IntPtr OCRStudioSDKImage_PageName(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateEmpty")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateEmpty();

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFile__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFile__SWIG_0(string jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFile__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFile__SWIG_1(string jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFile__SWIG_2")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFile__SWIG_2(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFile__SWIG_3")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFile__SWIG_3(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFileBuffer__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFileBuffer__SWIG_0([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFileBuffer__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFileBuffer__SWIG_1([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFileBuffer__SWIG_2")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFileBuffer__SWIG_2([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromFileBuffer__SWIG_3")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromFileBuffer__SWIG_3([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_0(string jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_1(string jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_2")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_2(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_3")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromBase64FileBuffer__SWIG_3(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromPixelBuffer")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromPixelBuffer([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromBuffer")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromBuffer([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromYUVSimple")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromYUVSimple([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CreateFromYUV")]
  public static extern global::System.IntPtr OCRStudioSDKImage_CreateFromYUV([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, int jarg3, int jarg4, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg5, int jarg6, int jarg7, int jarg8, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg9, int jarg10, int jarg11, int jarg12, int jarg13, int jarg14, int jarg15);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKImage")]
  public static extern void delete_OCRStudioSDKImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_DeepCopy")]
  public static extern global::System.IntPtr OCRStudioSDKImage_DeepCopy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_ShallowCopy")]
  public static extern global::System.IntPtr OCRStudioSDKImage_ShallowCopy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_Clear")]
  public static extern void OCRStudioSDKImage_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_ExportPixelBufferLength")]
  public static extern int OCRStudioSDKImage_ExportPixelBufferLength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_ExportPixelBuffer")]
  public static extern int OCRStudioSDKImage_ExportPixelBuffer(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.Out, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_ExportBase64JPEG")]
  public static extern global::System.IntPtr OCRStudioSDKImage_ExportBase64JPEG(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_Scale")]
  public static extern void OCRStudioSDKImage_Scale(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_DeepCopyScaled")]
  public static extern global::System.IntPtr OCRStudioSDKImage_DeepCopyScaled(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CropByQuad")]
  public static extern void OCRStudioSDKImage_CropByQuad(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_DeepCopyCroppedByQuad")]
  public static extern global::System.IntPtr OCRStudioSDKImage_DeepCopyCroppedByQuad(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_CropByRect")]
  public static extern void OCRStudioSDKImage_CropByRect(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_DeepCopyCroppedByRect")]
  public static extern global::System.IntPtr OCRStudioSDKImage_DeepCopyCroppedByRect(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_ShallowCopyCroppedByRect")]
  public static extern global::System.IntPtr OCRStudioSDKImage_ShallowCopyCroppedByRect(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_RotateByNinety")]
  public static extern void OCRStudioSDKImage_RotateByNinety(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_DeepCopyRotatedByNinety")]
  public static extern global::System.IntPtr OCRStudioSDKImage_DeepCopyRotatedByNinety(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_Width")]
  public static extern int OCRStudioSDKImage_Width(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_Height")]
  public static extern int OCRStudioSDKImage_Height(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_BytesPerLine")]
  public static extern int OCRStudioSDKImage_BytesPerLine(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_Channels")]
  public static extern int OCRStudioSDKImage_Channels(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_OwnsPixelData")]
  public static extern bool OCRStudioSDKImage_OwnsPixelData(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKImage_ForcePixelDataOwnership")]
  public static extern void OCRStudioSDKImage_ForcePixelDataOwnership(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKItem")]
  public static extern void delete_OCRStudioSDKItem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_DeepCopy")]
  public static extern global::System.IntPtr OCRStudioSDKItem_DeepCopy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Type")]
  public static extern string OCRStudioSDKItem_Type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Name")]
  public static extern string OCRStudioSDKItem_Name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Value")]
  public static extern string OCRStudioSDKItem_Value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Confidence")]
  public static extern double OCRStudioSDKItem_Confidence(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Accepted")]
  public static extern bool OCRStudioSDKItem_Accepted(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Attributes")]
  public static extern string OCRStudioSDKItem_Attributes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_HasImage")]
  public static extern bool OCRStudioSDKItem_HasImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Image")]
  public static extern global::System.IntPtr OCRStudioSDKItem_Image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItem_Description")]
  public static extern string OCRStudioSDKItem_Description(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKItemIterator")]
  public static extern void delete_OCRStudioSDKItemIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_new_OCRStudioSDKItemIterator")]
  public static extern global::System.IntPtr new_OCRStudioSDKItemIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItemIterator_IsEqualTo")]
  public static extern bool OCRStudioSDKItemIterator_IsEqualTo(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItemIterator_Next")]
  public static extern global::System.IntPtr OCRStudioSDKItemIterator_Next(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItemIterator_Step")]
  public static extern void OCRStudioSDKItemIterator_Step(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItemIterator_Key")]
  public static extern string OCRStudioSDKItemIterator_Key(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKItemIterator_Item")]
  public static extern global::System.IntPtr OCRStudioSDKItemIterator_Item(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKTarget")]
  public static extern void delete_OCRStudioSDKTarget(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_DeepCopy")]
  public static extern global::System.IntPtr OCRStudioSDKTarget_DeepCopy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_Description")]
  public static extern string OCRStudioSDKTarget_Description(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_ItemsCountByType")]
  public static extern int OCRStudioSDKTarget_ItemsCountByType(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_HasItem")]
  public static extern bool OCRStudioSDKTarget_HasItem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_Item")]
  public static extern global::System.IntPtr OCRStudioSDKTarget_Item(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_ItemsBegin")]
  public static extern global::System.IntPtr OCRStudioSDKTarget_ItemsBegin(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_ItemsEnd")]
  public static extern global::System.IntPtr OCRStudioSDKTarget_ItemsEnd(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKTarget_IsFinal")]
  public static extern bool OCRStudioSDKTarget_IsFinal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKResult")]
  public static extern void delete_OCRStudioSDKResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKResult_DeepCopy")]
  public static extern global::System.IntPtr OCRStudioSDKResult_DeepCopy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKResult_TargetsCount")]
  public static extern int OCRStudioSDKResult_TargetsCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKResult_TargetByIndex")]
  public static extern global::System.IntPtr OCRStudioSDKResult_TargetByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKResult_AllTargetsFinal")]
  public static extern bool OCRStudioSDKResult_AllTargetsFinal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKResult_Serialize")]
  public static extern global::System.IntPtr OCRStudioSDKResult_Serialize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKSession")]
  public static extern void delete_OCRStudioSDKSession(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_Description")]
  public static extern string OCRStudioSDKSession_Description(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_ProcessImage")]
  public static extern void OCRStudioSDKSession_ProcessImage(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_ProcessData")]
  public static extern void OCRStudioSDKSession_ProcessData(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_CurrentResult")]
  public static extern global::System.IntPtr OCRStudioSDKSession_CurrentResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_Reset")]
  public static extern void OCRStudioSDKSession_Reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_Suspend")]
  public static extern void OCRStudioSDKSession_Suspend(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKSession_Resume")]
  public static extern void OCRStudioSDKSession_Resume(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateStandalone__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateStandalone__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateStandalone__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateStandalone__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateFromPath__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateFromPath__SWIG_0(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateFromPath__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateFromPath__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateFromBuffer__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateFromBuffer__SWIG_0([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateFromBuffer__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateFromBuffer__SWIG_1([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_LibraryVersion")]
  public static extern string OCRStudioSDKInstance_LibraryVersion();

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_delete_OCRStudioSDKInstance")]
  public static extern void delete_OCRStudioSDKInstance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_Description")]
  public static extern string OCRStudioSDKInstance_Description(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateSession__SWIG_0")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateSession__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("csocrstudiosdk", EntryPoint="CSharp_ocrstudio_OCRStudioSDKInstance_CreateSession__SWIG_1")]
  public static extern global::System.IntPtr OCRStudioSDKInstance_CreateSession__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);
}

}
