//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ocrstudio {

  using ocrstudio;

public class OCRStudioSDKItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OCRStudioSDKItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OCRStudioSDKItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OCRStudioSDKItem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OCRStudioSDKItem() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csocrstudiosdkPINVOKE.delete_OCRStudioSDKItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual OCRStudioSDKItem DeepCopy() {
    global::System.IntPtr cPtr = csocrstudiosdkPINVOKE.OCRStudioSDKItem_DeepCopy(swigCPtr);
    OCRStudioSDKItem ret = (cPtr == global::System.IntPtr.Zero) ? null : new OCRStudioSDKItem(cPtr, false);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string Type() {
    string ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Type(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string Name() {
    string ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Name(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string Value() {
    string ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Value(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double Confidence() {
    double ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Confidence(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool Accepted() {
    bool ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Accepted(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string Attributes() {
    string ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Attributes(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool HasImage() {
    bool ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_HasImage(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual OCRStudioSDKImage Image() {
    OCRStudioSDKImage ret = new OCRStudioSDKImage(csocrstudiosdkPINVOKE.OCRStudioSDKItem_Image(swigCPtr), false);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string Description() {
    string ret = csocrstudiosdkPINVOKE.OCRStudioSDKItem_Description(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
