//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ocrstudio {

  using ocrstudio;

public class OCRStudioSDKString : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OCRStudioSDKString(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OCRStudioSDKString obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OCRStudioSDKString obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OCRStudioSDKString() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csocrstudiosdkPINVOKE.delete_OCRStudioSDKString(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public OCRStudioSDKString() : this(csocrstudiosdkPINVOKE.new_OCRStudioSDKString__SWIG_0(), true) {
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public OCRStudioSDKString(string c_str) : this(csocrstudiosdkPINVOKE.new_OCRStudioSDKString__SWIG_1(c_str), true) {
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public OCRStudioSDKString(OCRStudioSDKString copy) : this(csocrstudiosdkPINVOKE.new_OCRStudioSDKString__SWIG_2(OCRStudioSDKString.getCPtr(copy)), true) {
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public string CStr() {
    string ret = csocrstudiosdkPINVOKE.OCRStudioSDKString_CStr(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Size() {
    int ret = csocrstudiosdkPINVOKE.OCRStudioSDKString_Size(swigCPtr);
    if (csocrstudiosdkPINVOKE.SWIGPendingException.Pending) throw csocrstudiosdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
