//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ocrstudio {

public enum OCRStudioSDKPixelFormat {
  OCRSTUDIOSDK_PIXEL_FORMAT_G = 0,
  OCRSTUDIOSDK_PIXEL_FORMAT_GA,
  OCRSTUDIOSDK_PIXEL_FORMAT_AG,
  OCRSTUDIOSDK_PIXEL_FORMAT_RGB,
  OCRSTUDIOSDK_PIXEL_FORMAT_BGR,
  OCRSTUDIOSDK_PIXEL_FORMAT_BGRA,
  OCRSTUDIOSDK_PIXEL_FORMAT_ARGB,
  OCRSTUDIOSDK_PIXEL_FORMAT_RGBA
}

}
