//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ocrstudio {

public enum OCRStudioSDKYUVFormat {
  OCRSTUDIOSDK_YUV_FORMAT_NOT_SET = 0,
  OCRSTUDIOSDK_YUV_FORMAT_NV21,
  OCRSTUDIOSDK_YUV_FORMAT_420_888
}

}
